### ISSUE TITLE
Failure if too many repositories

### ISSUE THREAD

**Issue by OlivierMary** [otto-de/gitactionboard#7]
Hi,

I got a failure if too many repos:

```
2022-06-23 13:44:47.684 ERROR 1 --- [onPool-worker-3] d.o.p.g.a.s.w.GithubWorkflowService      : org.springframework.web.client.HttpClientErrorException: 414 URI Too Long: [no body]

java.util.concurrent.CompletionException: org.springframework.web.client.HttpClientErrorException: 414 URI Too Long: [no body]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
Caused by: org.springframework.web.client.HttpClientErrorException: 414 URI Too Long: [no body]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:145) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:334) ~[spring-web-5.3.20.jar!/:5.3.20]
	at de.otto.platform.gitactionboard.adapters.service.ApiService.getForObject(ApiService.java:37) ~[classes!/:2.0.7]
	at de.otto.platform.gitactionboard.adapters.service.workflow.GithubWorkflowService.getWorkflowIdentifiers(GithubWorkflowService.java:44) ~[classes!/:2.0.7]
	at de.otto.platform.gitactionboard.adapters.service.workflow.GithubWorkflowService.lambda$fetchWorkflows$1(GithubWorkflowService.java:30) ~[classes!/:2.0.7]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
	... 6 common frames omitted
```

**Comment by sumanmaity1234** [comment]
Hi @OlivierMary, 
There are no relation between number of repos with the length of URI. For each repository, it'll make following API call to workflows and jobs.

Can you check **REPO_NAMES** configuration

**Comment by sumanmaity1234** [comment]
Closing this issue due to inactivity. Feel free open this ticket if you encounter similar issue
